"""add sale fields and mpesa_messages

Revision ID: 3c98183be872
Revises: e96412dda01c
Create Date: 2026-07-28 23:27:05.085193
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3c98183be872'
down_revision: Union[str, None] = 'e96412dda01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_messages_business_id'), 'mpesa_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_mpesa_messages_id'), 'mpesa_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_messages_reference'), 'mpesa_messages', ['reference'], unique=False)
    op.create_index(op.f('ix_mpesa_messages_transaction_id'), 'mpesa_messages', ['transaction_id'], unique=False)
    op.add_column('transactions', sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('change_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'change_amount')
    op.drop_column('transactions', 'amount_received')
    op.drop_index(op.f('ix_mpesa_messages_transaction_id'), table_name='mpesa_messages')
    op.drop_index(op.f('ix_mpesa_messages_reference'), table_name='mpesa_messages')
    op.drop_index(op.f('ix_mpesa_messages_id'), table_name='mpesa_messages')
    op.drop_index(op.f('ix_mpesa_messages_business_id'), table_name='mpesa_messages')
    op.drop_table('mpesa_messages')
    # ### end Alembic commands ###
