"""wire_transactions_to_businesses

Revision ID: e96412dda01c
Revises: 85610e69a0f3
Create Date: 2026-07-26 11:48:35.223376
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e96412dda01c'
down_revision: Union[str, None] = '85610e69a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.drop_constraint(op.f('ledger_entries_reference_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ledger_entries', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('ledger_entries', 'reference_id')
    op.add_column('transactions', sa.Column('business_id', sa.Integer(), nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_transactions_business_id'), 'transactions', ['business_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_business_id'), table_name='transactions')
    op.alter_column('transactions', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('transactions', 'business_id')
    op.add_column('ledger_entries', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(op.f('ledger_entries_reference_id_fkey'), 'ledger_entries', 'transactions', ['reference_id'], ['id'])
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'transaction_id')
    # ### end Alembic commands ###
